# Generated by Django 3.2 on 2021-05-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(help_text='Unit for current Ingredient', on_delete=django.db.models.deletion.RESTRICT, related_name='Ingredient', to='foods.unit', verbose_name='Ingredient unit'),
        ),
    ]
