# Generated by Django 3.2.3 on 2021-05-24 11:50

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Create three tags in the moment model is created in DB
    """
    Tag = apps.get_model("recipes", "Tag")
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).bulk_create([
        Tag(name="Завтрак", slug="breakfast"),
        Tag(name="Обед", slug="lunch"),
        Tag(name="Ужин", slug="dinner"),
    ])


def reverse_func(apps, schema_editor):
    """
    Method for the situation if tags model would be deleted
    """
    Tag = apps.get_model("recipes", "Tag")
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).filter(name="Завтрак",).delete()
    Tag.objects.using(db_alias).filter(name="Обед",).delete()
    Tag.objects.using(db_alias).filter(name="Ужин", ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Recipe tag name')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='Tag slug for forms and imputs')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recipes.Tag'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
