# Generated by Django 3.2 on 2021-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='Cooking time in minutes'),
            preserve_default=False,
        ),
    ]
