# Generated by Django 3.2 on 2021-05-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Recipes slug, a part of detail page URL'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
