# Generated by Django 3.2 on 2021-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210511_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag_supper',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag_lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
    ]
